### ISSUE TITLE
Can't install 1.1.0 for Swift 3

### ISSUE THREAD

**Issue by xiaosongshu** [blackmirror-media/BMPickerModal#6]
Is 1.1.0 live yet?

pod 'BMPickerModal', '~>1.1.0' erroring out

```

[!] Unable to satisfy the following requirements:

- `BMPickerModal (~> 1.1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `BMPickerModal (~> 1.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by eriadam** [comment]
Hello. No, not yet. It is a pre-release. When the GM is out from the new versions, I will make a release of this.

Until that, you can install using:

`pod 'BMPickerModal', :git => 'https://github.com/blackmirror-media/BMPickerModal.git', :branch => 'release/1.1.0'`

**Comment by xiaosongshu** [comment]
Hi there, given GM is out now, any idea when full support will be ready :)

**Comment by eriadam** [comment]
@xiaosongshu The latest changes (GM) are in the release branch. Still testing and will release in the next days.
